.TH "DataLoader.Metadata" 3 "Wed Aug 5 2020" "datalogger-GUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataLoader.Metadata
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, path, start, end, completed=True)"
.br
.ti -1c
.RI "def \fBprint\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpath\fP"
.br
.ti -1c
.RI "\fBstart\fP"
.br
.ti -1c
.RI "\fBend\fP"
.br
.ti -1c
.RI "\fBcompleted\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class to store basic metadata of CSV files
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def DataLoader\&.Metadata\&.__init__ ( self,  path,  start,  end,  completed = \fCTrue\fP)"

.PP
.nf
The constructor
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def DataLoader\&.Metadata\&.print ( self)"

.PP
.nf
Print metadata
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for datalogger-GUI from the source code\&.
