.TH "DateTimePicker.DateTimePicker" 3 "Wed Aug 5 2020" "datalogger-GUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DateTimePicker.DateTimePicker
.SH SYNOPSIS
.br
.PP
.PP
Inherits QMainWindow, and Ui_DateTimePicker\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, parent, button, defaultDateTime=None)"
.br
.ti -1c
.RI "def \fBupdateDatetime\fP (self)"
.br
.ti -1c
.RI "def \fBupdateTime\fP (self, time)"
.br
.ti -1c
.RI "def \fBpassDateTime\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbutton\fP"
.br
.ti -1c
.RI "\fBparent\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for datalogger-GUI from the source code\&.
