.TH "main.MyApp" 3 "Wed Aug 5 2020" "datalogger-GUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.MyApp
.SH SYNOPSIS
.br
.PP
.PP
Inherits QMainWindow, and Ui_MainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBplotData\fP (self)"
.br
.ti -1c
.RI "def \fBonStartDateTimeClicked\fP (self)"
.br
.ti -1c
.RI "def \fBonEndDateTimeClicked\fP (self)"
.br
.ti -1c
.RI "def \fBonDateTimeChanged\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdata\fP"
.br
.ti -1c
.RI "\fBstartDateTimePicker\fP"
.br
.ti -1c
.RI "\fBendDateTimePicker\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for datalogger-GUI from the source code\&.
