.TH "MplWidget.MplWidget" 3 "Wed Aug 5 2020" "datalogger-GUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MplWidget.MplWidget
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, parent=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcanvas\fP"
.br
.ti -1c
.RI "\fBtoolbar\fP"
.br
.ti -1c
.RI "\fBvbl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Widget defined in Qt Designer
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def MplWidget\&.MplWidget\&.__init__ ( self,  parent = \fCNone\fP)"

.PP
.nf
The constructor
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for datalogger-GUI from the source code\&.
