.TH "MplWidget.MplCanvas" 3 "Wed Aug 5 2020" "datalogger-GUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MplWidget.MplCanvas
.SH SYNOPSIS
.br
.PP
.PP
Inherits FigureCanvas\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBsetLayout\fP (self, layout)"
.br
.ti -1c
.RI "def \fBcla\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfig\fP"
.br
.ti -1c
.RI "\fBax\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class to represent the FigureCanvas widget
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def MplWidget\&.MplCanvas\&.__init__ ( self)"

.PP
.nf
The constructor
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def MplWidget\&.MplCanvas\&.cla ( self)"

.PP
.nf
Clear all axes of all subplots in figure
.fi
.PP
 
.SS "def MplWidget\&.MplCanvas\&.setLayout ( self,  layout)"

.PP
.nf
Set number and arragement of subplots according to
data column count
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for datalogger-GUI from the source code\&.
